# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json
description: API_Scanning
targets:
  - id: http
    config:
      url: http://192.168.154.156:3000/api/chat/completions
      method: POST
      headers:
        Authorization: Bearer sk-30946b3e82b44fb0a6e112b90411adc6
        Content-Type: application/json
      body: |-
        {
        "model": "qwen-with-mitigations",
        "messages": [{"role": "user","content": "{{prompt}}"}]
        }
      useHttps: false
    label: qwen model
prompts:
  - '{{prompt}}'
redteam:
  purpose: |-
    The objective of the application is: You are a chatbot. You respond to user's input by providing useful responses.

    You are: You are a user of a chatbot
  entities:
    - '{{prompt}}'
  plugins:
    - id: bola  # Tests for broken object-level authorization vulnerabilities (OWASP API 1)
    - id: rbac  # Tests role-based access control implementation
    - id: bfla  # Tests for broken function-level authorization vulnerabilities (OWASP API 5)
    - id: excessive-agency  # Tests for unauthorized actions beyond defined system boundaries
    - id: overreliance  # Tests for overreliance on system assumptions
    - id: harmful:privacy  # Tests handling of privacy violation attempts
    - id: pii:api-db  # Tests for PII exposure via API/database access
    - id: pii:session  # Tests for PII exposure in session data
    - id: harmful:misinformation-disinformation  # Tests handling of false information campaigns
    - id: shell-injection  # Tests for command injection vulnerabilities
    - id: sql-injection  # Tests for SQL injection vulnerabilities
    - id: harmful:specialized-advice  # Tests handling of unauthorized professional advice
    - id: debug-access  # Tests for exposed debugging interfaces and commands
  strategies:
    - id: basic  # Original plugin tests without any additional strategies or optimizations
    - id: jailbreak  # Single-shot optimization of safety bypass techniques
    - id: jailbreak:composite  # Combines multiple jailbreak techniques for enhanced effectiveness
    - id: jailbreak:likert  # Uses Likert scale-based prompts to bypass content filters
defaultTest:
  options:
    transformVars: '{ ...vars, sessionId: context.uuid }'
