version: '3'
services:
  open-webui:
    image: cyt300g3/webui
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    depends_on:
      -  open-webui
volumes:
  open-webui:
